plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.lime'
version = '0.0.1-SNAPSHOT'
description = 'mukbbo-map'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'ch.hsr:geohash:1.4.0'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Swagger/OpenAPI (Spring Boot 4 호환)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-webmvc-test
    testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test:4.0.2")

    //search
    // Source: https://mvnrepository.com/artifact/co.elastic.clients/elasticsearch-java
    implementation("co.elastic.clients:elasticsearch-java:9.2.4")

    // Apache HttpClient 5 (최신 버전)
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'

    // Elasticsearch Low Level REST Client
    implementation 'org.elasticsearch.client:elasticsearch-rest-client:8.11.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('copySecret', Copy) {
    from './mukbbo-private'
    include "application.yml"
    into './src/main/resources'
}

tasks.register('copyTestSecret', Copy) {
    from('./mukbbo-private') {
        include 'application-test.yml'
        rename 'application-test.yml', 'application.yml'
    }
    into './src/test/resources'
}

processResources.dependsOn('copySecret')
processTestResources.dependsOn('copyTestSecret')